name: CryptoMiner
version: '${project.version}'
main: me.lownzy.cryptominer.cryptoMiner
api-version: '1.20'

commands:
  printer:
    description: Gives the player a Money Printer
    usage: /printer
    executor: me.lownzy.cryptominer.Commands.printerGiver

  statechecker:
    description: Check the state of a block
    usage: /statechecker
    executor: me.lownzy.cryptominer.Commands.StateChecker
